# SemEval-2020 Task 4: Commonsense Validation and Explanation

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1rlwPIErsvGcYYgM6s_FT9FDn9lcHzvVU?usp=sharing)

# 0. Getting started

In [ ]:
!nvidia-smi

Sun May 16 00:08:57 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   75C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [2]:
%cd /content/gdrive/MyDrive/fer-tar

/content/gdrive/.shortcut-targets-by-id/1drN2cinzIyZ4ThABotRYWgVJfNq9n-5w/fer-tar


In [3]:
!pip install -q pytorch_lightning
!pip install -q transformers

     |████████████████████████████████| 808kB 8.5MB/s 
     |████████████████████████████████| 112kB 34.1MB/s 
     |████████████████████████████████| 645kB 40.3MB/s 
     |████████████████████████████████| 829kB 52.4MB/s 
     |████████████████████████████████| 276kB 50.6MB/s 
     |████████████████████████████████| 1.3MB 49.9MB/s 
     |████████████████████████████████| 296kB 49.3MB/s 
     |████████████████████████████████| 143kB 54.3MB/s 
     |████████████████████████████████| 2.3MB 8.2MB/s 
     |████████████████████████████████| 901kB 51.7MB/s 
     |████████████████████████████████| 3.3MB 51.3MB/s 


## 0.1. Imports

In [ ]:
import importlib
import src.models
importlib.reload(src.models)

<module 'src.models' from '/content/gdrive/.shortcut-targets-by-id/1drN2cinzIyZ4ThABotRYWgVJfNq9n-5w/fer-tar/src/models.py'>

In [4]:
import pytorch_lightning as pl
from torch.utils.data import DataLoader
from my_scripts import data
from src import encoders
from src.models import BertClassifier

In [5]:
BATCH_SIZE = 32
EPOCHS = 15

In [6]:
train_ds, val_ds, test_ds = data.ComVEDataset.from_data_folder(x_transforms=[encoders.BertEncoder()])
train_dataloader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
val_dataloader = DataLoader(val_ds, batch_size=len(val_ds))

from pytorch_lightning.callbacks.early_stopping import EarlyStopping
early_stop_callback = EarlyStopping(
   monitor='val_acc',
   min_delta=0.00,
   patience=5,
   verbose=False,
   mode='max'
)

model = BertClassifier()
trainer = pl.Trainer(max_epochs=EPOCHS, gpus=1, progress_bar_refresh_rate=20, callbacks=[EarlyStopping(monitor='val_loss')])
trainer.fit(model, train_dataloader, val_dataloader)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name        | Type      | Params
--

tensor([[-0.8187, -0.4951, -0.8710,  ..., -0.8221, -0.6989,  0.6848],
        [-0.8532, -0.4772, -0.9619,  ..., -0.8836, -0.7625,  0.7257],
        [-0.8580, -0.4910, -0.8467,  ..., -0.7539, -0.7192,  0.7521],
        ...,
        [-0.9481, -0.5536, -0.7328,  ..., -0.1223, -0.7903,  0.9498],
        [-0.6631, -0.0951,  0.4133,  ...,  0.3248, -0.4802,  0.8099],
        [-0.6880, -0.2269, -0.2984,  ...,  0.1437, -0.5509,  0.8389]],
       device='cuda:0')
torch.Size([997, 768])
torch.Size([997, 768])


/content/gdrive/.shortcut-targets-by-id/1drN2cinzIyZ4ThABotRYWgVJfNq9n-5w/fer-tar/src/models.py:48: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  acc = torch.tensor((predictions == y_batch).float()).mean()


tensor([[-0.7433, -0.3317, -0.5954,  ..., -0.3961, -0.5286,  0.6616],
        [-0.8603, -0.2486, -0.2096,  ...,  0.0085, -0.6660,  0.8671],
        [-0.9037, -0.5260, -0.9647,  ..., -0.9182, -0.8227,  0.9241],
        ...,
        [-0.7999, -0.1787,  0.5748,  ...,  0.4539, -0.5435,  0.7433],
        [-0.7867, -0.4267, -0.9255,  ..., -0.7802, -0.7507,  0.7914],
        [-0.7762, -0.1443, -0.7648,  ..., -0.7090, -0.5523,  0.8106]],
       device='cuda:0', grad_fn=<TanhBackward>)
torch.Size([32, 768])
torch.Size([32, 768])
tensor([[-0.9370, -0.4503, -0.9393,  ..., -0.7909, -0.7438,  0.9526],
        [-0.8451, -0.3740, -0.8364,  ..., -0.8431, -0.6234,  0.8175],
        [-0.6299, -0.2465, -0.1332,  ..., -0.3571, -0.5815,  0.6789],
        ...,
        [-0.8878, -0.3212, -0.6851,  ..., -0.6688, -0.6788,  0.7732],
        [-0.9377, -0.4955, -0.9701,  ..., -0.8730, -0.7683,  0.9479],
        [-0.7752, -0.2797, -0.7923,  ..., -0.6870, -0.6486,  0.8261]],
       device='cuda:0', grad_fn=<TanhBac

/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py:69: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  warnings.warn(*args, **kwargs)


## 0.2. Getting the data

## 0.3. Preprocessing